### ISSUE TITLE
Unable to run the package

### ISSUE THREAD

**Issue by yihungkuo** [jkrasting/mdtf_test_data#5]
@jkrasting I successfully installed the package following the instructions but could not get it work. Attached are the commands I ran for setting up the environment, installing and running the package.

_Set up the environment with the required dependencies_:
`conda create -n xesmf_env python=3.7`
`source activate xesmf_env`
`conda install -c conda-forge esmpy xarray scipy dask netCDF4 numpy cftime xesmf`

_Install the package_:
`git clone https://github.com/jkrasting/mdtf_test_data.git`
`cd mdtf_test_data`
`pip install .`

Processing /home/yhkuo/mdtf/mdtf_test_data
Requirement already satisfied: cftime in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (1.3.0)
Requirement already satisfied: numpy in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (1.19.2)
Requirement already satisfied: setuptools>=41.2 in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (50.3.2.post20201201)
Requirement already satisfied: xarray in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (0.16.2)
Requirement already satisfied: xesmf in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (0.2.0)
Requirement already satisfied: numpy in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (1.19.2)
Requirement already satisfied: pandas>=0.25 in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from xarray->mdtf-test-data==0.0.1) (1.1.4)
Requirement already satisfied: numpy in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (1.19.2)
Requirement already satisfied: setuptools>=41.2 in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (50.3.2.post20201201)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from pandas>=0.25->xarray->mdtf-test-data==0.0.1) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from pandas>=0.25->xarray->mdtf-test-data==0.0.1) (2020.4)
Requirement already satisfied: numpy in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (1.19.2)
Requirement already satisfied: six>=1.5 in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.25->xarray->mdtf-test-data==0.0.1) (1.15.0)
Requirement already satisfied: scipy in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from xesmf->mdtf-test-data==0.0.1) (1.5.3)
Requirement already satisfied: numpy in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (1.19.2)
Requirement already satisfied: esmpy in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from xesmf->mdtf-test-data==0.0.1) (8.0.0)
Requirement already satisfied: xarray in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (0.16.2)
Requirement already satisfied: numpy in /home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages (from mdtf-test-data==0.0.1) (1.19.2)
Building wheels for collected packages: mdtf-test-data
  Building wheel for mdtf-test-data (setup.py) ... done
  Created wheel for mdtf-test-data: filename=mdtf_test_data-0.0.1-py3-none-any.whl size=16582 sha256=ae0469a0f0659bac757d1165a2153e6b146988c0f85285c913abe2ab7acdb2df
  Stored in directory: /tmp/pip-ephem-wheel-cache-eiv8uzz6/wheels/db/b5/a4/ff27f83b8bb0028d3e206543ce9506ddf7101b010d1c89e25c
Successfully built mdtf-test-data
Installing collected packages: mdtf-test-data
Successfully installed mdtf-test-data-0.0.1

_Try to run the package & error messages_:
`~/mdtf/mdtf_test_data$ ./scripts/ncar_synthetic.py`
./scripts/ncar_synthetic.py: line 1:  Script to generate synthetic NCAR CESM2 output : command not found
./scripts/ncar_synthetic.py: line 3: import: command not found
./scripts/ncar_synthetic.py: line 5: import: command not found
./scripts/ncar_synthetic.py: line 7: DLON: command not found
./scripts/ncar_synthetic.py: line 8: DLAT: command not found
./scripts/ncar_synthetic.py: line 9: STARTYEAR: command not found
./scripts/ncar_synthetic.py: line 10: NYEARS: command not found
./scripts/ncar_synthetic.py: line 12: CASENAME: command not found
./scripts/ncar_synthetic.py: line 14: syntax error near unexpected token \`f"{CASENAME}/mon"'
./scripts/ncar_synthetic.py: line 14: \`os.makedirs(f"{CASENAME}/mon")'

`~/mdtf/mdtf_test_data$ ./scripts/gfdl_synthetic.py`
./scripts/gfdl_synthetic.py: line 1:  Script to generate synthetic GFDL CM4 output : command not found
./scripts/gfdl_synthetic.py: line 3: import: command not found
./scripts/gfdl_synthetic.py: line 5: import: command not found
./scripts/gfdl_synthetic.py: line 7: DLON: command not found
./scripts/gfdl_synthetic.py: line 8: DLAT: command not found
./scripts/gfdl_synthetic.py: line 9: STARTYEAR: command not found
./scripts/gfdl_synthetic.py: line 10: NYEARS: command not found
./scripts/gfdl_synthetic.py: line 12: CASENAME: command not found
./scripts/gfdl_synthetic.py: line 15: syntax error near unexpected token \`f"{CASENAME}/day"'
./scripts/gfdl_synthetic.py: line 15: \`os.makedirs(f"{CASENAME}/day")'

`~/mdtf/mdtf_test_data$ mdtf-coarsen.py -o ~/mdtf/inputdata/model/QBOi.EXP1.AMIP.001/test.nc ~/mdtf/inputdata/model/QBOi.EXP1.AMIP.001/1hr/QBOi.EXP1.AMIP.001.PRECT.1hr.nc`
/home/yhkuo/anaconda3/envs/xesmf_env/bin/mdtf-coarsen.py: line 1:  CLI script for coarsening datasets for MDTF : command not found
/home/yhkuo/anaconda3/envs/xesmf_env/bin/mdtf-coarsen.py: line 3: import: command not found
/home/yhkuo/anaconda3/envs/xesmf_env/bin/mdtf-coarsen.py: line 4: import: command not found
/home/yhkuo/anaconda3/envs/xesmf_env/bin/mdtf-coarsen.py: line 5: import: command not found
/home/yhkuo/anaconda3/envs/xesmf_env/bin/mdtf-coarsen.py: line 7: import: command not found
from: can't read /var/mail/mdtf_test_data.coarsen
/home/yhkuo/anaconda3/envs/xesmf_env/bin/mdtf-coarsen.py: line 16: syntax error near unexpected token \`action="ignore",'
/home/yhkuo/anaconda3/envs/xesmf_env/bin/mdtf-coarsen.py: line 16: \`warnings.simplefilter(action="ignore", category=FutureWarning)'

**Comment by jkrasting** [comment]
Sorry about that @yihungkuo - I pushed my last update to the wrong branch.   Please give it another try now.

**Comment by yihungkuo** [comment]
@jkrasting It works now. But the mdtf-coarsen.py still doesn't work with the QBOi data:

`~/mdtf/mdtf_test_data$ mdtf-coarsen.py -o ~/mdtf/inputdata/model/QBOi.EXP1.AMIP.001/test.nc ~/mdtf/inputdata/model/QBOi.EXP1.AMIP.001/1hr/QBOi.EXP1.AMIP.001.PRECT.1hr.nc`
/home/yhkuo/mdtf/inputdata/model/QBOi.EXP1.AMIP.001/1hr/QBOi.EXP1.AMIP.001.PRECT.1hr.nc
Traceback (most recent call last):
  File "/home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/coding/times.py", line 113, in _decode_cf_datetime_dtype
    result = decode_cf_datetime(example_value, units, calendar, use_cftime)
  File "/home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/coding/times.py", line 218, in decode_cf_datetime
    flat_num_dates.astype(float), units, calendar
  File "/home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/coding/times.py", line 134, in _decode_datetime_with_cftime
    cftime.num2date(num_dates, units, calendar, only_use_cftime_datetimes=True)
  File "cftime/_cftime.pyx", line 495, in cftime._cftime.num2date
  File "cftime/_cftime.pyx", line 147, in cftime._cftime._dateparse
  File "cftime/_cftime.pyx", line 981, in cftime._cftime.datetime.__init__
ValueError: calendar must be one of ['standard', 'gregorian', 'proleptic_gregorian', 'noleap', 'julian', 'all_leap', '365_day', '366_day', '360_day'], got 'noleap                                                                                                                                                                                                                                                          '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yhkuo/anaconda3/envs/xesmf_env/bin/mdtf-coarsen.py", line 57, in <module>
    dset = xr.open_dataset(_infile,use_cftime=True)
  File "/home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/backends/api.py", line 575, in open_dataset
    ds = maybe_decode_store(store, chunks)
  File "/home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/backends/api.py", line 479, in maybe_decode_store
    decode_timedelta=decode_timedelta,
  File "/home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/conventions.py", line 598, in decode_cf
    decode_timedelta=decode_timedelta,
  File "/home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/conventions.py", line 500, in decode_cf_variables
    decode_timedelta=decode_timedelta,
  File "/home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/conventions.py", line 340, in decode_cf_variable
    var = times.CFDatetimeCoder(use_cftime=use_cftime).decode(var, name=name)
  File "/home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/coding/times.py", line 463, in decode
    dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)
  File "/home/yhkuo/anaconda3/envs/xesmf_env/lib/python3.7/site-packages/xarray/coding/times.py", line 123, in _decode_cf_datetime_dtype
    raise ValueError(msg)
ValueError: unable to decode time units 'days since 1975-01-01 00:00:00' with "calendar 'noleap                                                                                                                                                                                                                                                          '". Try opening your dataset with decode_times=False or installing cftime if it is not installed.

**Comment by jkrasting** [comment]
Oh, I should have mentioned this - some of the NCAR and GFDL datasets have non-standard calendar attributes that are incompatible with cftime and xarray.   Here are two updated (full-resolution) datasets.   Coarsening these data with the tool will work.

```
ftp://ftp.gfdl.noaa.gov/pub/John.Krasting/mdtf/model.QBOi.EXP1.AMIP.001.20201122.tar
ftp://ftp.gfdl.noaa.gov/pub/John.Krasting/mdtf/model.GFDL.CM4.c96L32.am4g10r8.20201122.tar
```

**Comment by yihungkuo** [comment]
Downloading the data. Will test again later today.

A more general question: Can POD developers safely assume standard calendar attributes that are compatible with cftime and xarray? Or PODs should be able to handle more general cases? Should the framework consider to provide supporting utility functions for PODs to assess the data (so that PODs do not need to worry about the attributes, etc.)?

**Comment by jkrasting** [comment]
Looks like a corrupted/interrupted download.  Verify the sizes and checksums:

```
-rw-r--r--. 1 John.Krasting o  5147234304 Dec  5 09:17 model.GFDL.CM4.c96L32.am4g10r8.20201122.tar
-rw-r--r--. 1 John.Krasting o 13207336960 Nov 22 15:18 model.QBOi.EXP1.AMIP.001.20201122.tar

20abfca66620081fc69c47f0c7f6a26c  model.GFDL.CM4.c96L32.am4g10r8.20201122.tar
7dfa30e1c043e94b06f0de34b8eb0e0d  model.QBOi.EXP1.AMIP.001.20201122.tar
```

I don't fully understand the calendar question. I think relying on Xarray as @ahmedfiaz suggested is good practice.  One suggestion to the [example notebook](https://gist.github.com/ahmedfiaz/58b36a0a1ea6ad39bc1fd91067b4fb91) presented back in November would be to add the `use_cftime=True` option when calling `xarray.open_dataset.`

**Comment by yihungkuo** [comment]
@jkrasting I finally successfully tested the mdtf-coarsen.py script with the GFDL.CM4 sample data. It works.

Two quick remarks.
1) I tried to download the sample data, but kept getting interrupted (bad internet connection maybe). Went to my office and tried again, the QBOi sample still failed.
For the upcoming MDTF v3 release, during the COVID time, we should think ahead about how sample model data are shared, especially when data size is large. Some data sharing mechanisms that allow resuming download after interruption (e.g., rsync or via dropbox) would be preferable.

2) About the calendar question. Sorry for the confusion. I just want to confirm whether POD developers should include the `use_cftime=True` option (or something equivalent) as mandatory in their scripts so to benefit from utility functions like mdtf_test_data. Also, before submitting their PODs, do they need to test with data that are compatible/non-compatible with CF calendar convention?
